# Generated by Django 5.0.6 on 2024-07-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=122)),
                ('LastName', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Phone', models.CharField(max_length=122)),
                ('desc', models.CharField(max_length=122)),
                ('City', models.CharField(max_length=122)),
                ('inputState', models.CharField(choices=[('AP', 'Aunachal Pradesh'), ('UP', 'Uttar Pradesh'), ('Mp', 'Madhya Pradesh')], default='UP', max_length=122)),
                ('inputZip', models.CharField(max_length=122)),
            ],
        ),
    ]
